### ISSUE TITLE
[NFR] Add setting to cleanup PO settings that the user shoudn't be able to see

### ISSUE THREAD

**Issue by dschissler** [perchlayer/po-loader#1]
Currently a lot of information is sent over in the JSON file from the PO file.  There should be an option to clean this up.

**Comment by dschissler** [comment]
The new po2json solves this.  Used `json!po?format=jed` in the po-loader webpack.config to send a cleaned up output.

**Comment by saadaouad** [comment]
Thanks @dschissler for this useful,  
Great 👍

**Comment by dschissler** [comment]
@saadaouad This was from a while ago so you'll probably want to be using `jed1.x` now.  It might even be required to use the latest libraries.

**Comment by saadaouad** [comment]
I'm working just with the modules `json-loader`, `po-loader` and `po2json`.
Can you see the usage for how i can use my message in the JSX file : 

Import our file .po :
`import t from 'fugoki/core/locale/ar.po`

Inject words :
`{t['text_msgid']}`

Get :
`msgstr`

**Comment by dschissler** [comment]
Webpack 1 or 2?

**Comment by dschissler** [comment]
For Webpack 2.  If you are using Webpack 1 then just make the query object be a string.

* https://github.com/perchlayer/webird/blob/master/dev/webpack.js#L161-L167
* https://github.com/perchlayer/webird/blob/master/app/webpack/modules/locale/locale.js

First try getting it to work from plain Javascript then try from templates as that is dramatically more complex.

So then once you have your messages loading then you will be faced with an issue of how to dynamically change the language based on the user's browser settings.  For this you can use Webpack as an inlined build step that will build all of your languages at the same time that you are defining the logic.

https://github.com/perchlayer/webird/blob/master/app/webpack/modules/locale/locale.js#L74

You won't be able to use ES6 import for this.  Webpack will build everything by substituting `locale` for `*` and then it will keep track of the directory names used so that at runtime you can request a locale and if it isn't present then during runtime it will throw an exception and you can try again.

**Comment by saadaouad** [comment]
Ok, thanks for your support @dschissler 👍
