### ISSUE TITLE
This doesn't work wih Babel 6

### ISSUE THREAD

**Issue by dschissler** [perchlayer/po-loader#3]
Beware anyone trying to upgrade to Babel 6 because there are issues.

**Comment by landabaso** [comment]
Strange. I'm using it with babel 6 and it works for me.
`"babel-core": "^6.6.0"`
What kind of problems?

**Comment by dschissler** [comment]
Oops.  This was from a few months ago.

**Comment by landabaso** [comment]
I was not going to install it because of this comment :-)

**Comment by dschissler** [comment]
Sorry.  Actually the issue is within `babel-loader`.  It isn't resolving things the same way that it used to and it is necessary to use `require.resolve` in some situations.  I'm not able to feed in the locale module into my template helper because they are compiled at build time.  So I'm changing my messages from `{{ t('english message') }}` to `english message` and then I'll have to go back through once this is fixed.  Alternatively I could downgrade to Babel 5.  I'm hoping that once Webpack 2 is released that this will all be fixed within a few months since people will be wanting to use tree shaking and this will require Babel 6.

**Comment by DHFW** [comment]
Hi, I've a few questions.

1. Is it correct that I should install po2json manually? It is not loaded as a dependency, so I think it cannot work?

2. Regarding this, I try to use it with babel-loader and "babel-core": "^6.6.0", but I get errors: Module not found: Error: Cannot resolve 'file' or 'directory'. Do you know how to solve this?

You seem to have the only webpack loader that supports dynamically loaded translation files and I want it to get it working...
Thnx!

**Comment by dschissler** [comment]
I can use po-loader in Javascript just fine but I can't use it within my Nunjucks templates that were compiled at build time.  So it looks like `{{ t('Search Here') }}`.  This also affects me being able to use the Bluebird promise polyfill.  The solution is to just go ahead and develop and home it is ready on production or to downgrade back to the 5 series.

**Comment by dschissler** [comment]
Sorry I didn't answer your questions exactly:

1) `po2json` is a `peerDependency` and with npm3+ it is necessary to include it in your package.json.

2) I answered this in my previous post.

**Comment by dschissler** [comment]
@DHFW Also there currently isn't much real benefit to using Babel 6 so its not terrible to downgrade to 5.  The only benefit that I can see over the next 6 months are being to use Webpack 2 with tree shaking which requires Babel 6 and to instead use the webpack preset instead of the default one.  Also Safari is so miserable in its support of new features that this is holding everything back and makes the Babel 6 ability to turn off individual conversions to be for me at least a moot point.  Babel 5 is basically perfect for today's use.
