### ISSUE TITLE
How to use this with webpack 3?

### ISSUE THREAD

**Issue by mackbrowne** [perchlayer/po-loader#8]
i'm pretty sure i have it included in my config correctly, but how do i reference the generated json files in my code?  how do i import them?  do the json files get generated alongside where the po files are?

**Comment by dschissler** [comment]
Its the same as with Webpack 1 & 2.  The `json-loader` will return script that Webpack can use to create a bundle.

The following code from the readme will use a wildcard (locale) to process all of the files which match that pattern (all of the locales).

```javascript
function getLangLoader(locale) {
  return require("bundle!" + LOCALE_ROOT + "/" + locale + "/LC_MESSAGES/messages.po");
};
```

Then during runtime if you request a locale that is not available then it will throw an exception and you can try again.

```javascript
      if (multipart) {
        try {
          waitForLangChunk = getLangLoader(language);
        } catch (error) {
          eLanguage = error;
          waitForLangChunk = getLangLoader(LOCALE_DEFAULT);
        }
      } else {
        waitForLangChunk = getLangLoader(LOCALE_DEFAULT);
      }
```

This outputs into your normal webpack output directory.
